title: The Lodge
description: UW Law and Environmental Graduate Student Collaboration - Field trips, education, and stakeholder engagement in natural resources and environmental stewardship
baseurl: "/thelodge"
url: "https://clinton-alden.github.io"
author: The Lodge Collective

# Build settings
markdown: kramdown
theme: minima

# Exclude files from Jekyll processing
exclude:
  - .gitignore
  - README.md
